### ISSUE TITLE
don't we need install ovs or nsx-cni on this version?

### ISSUE THREAD

**Issue by joungwoongpark** [dumlutimuralp/k8s-with-nsx-t-2.5.x#1]
Thank you for your posts on github.
Your posts really help a lot to me.
I also did k8s-with-nsx-t-2.4.x. and I noticed there was something Defferences between 2.4.x and 2.5.x
as I read 2.5.x, There is no comment about install nsx-cni and OVS.
Don't we need to install them If we use  k8s-with-nsx-t-2.5.x??
It is first time integrating k8s with nsx. So I don't know about it much.

**Comment by dumlutimuralp** [comment]
Thanks for the comment. 
No, you do not install nsx-cni and OVS manually anymore. Both of those components are installed by the NCP Bootstrap daemonset automatically. Please read part 2 of the series, it is explained  there in detail.
https://github.com/dumlutimuralp/k8s-with-nsx-t-2.5.x/blob/master/Part%202/README.md
