### ISSUE TITLE
Don't we need to install cni on ncp 2.5.0 and 2.5.1 version??

### ISSUE THREAD

**Issue by joungwoongpark** [dumlutimuralp/k8s-with-nsx-t-2.5.x#4]
I have a question.
In case of ncp 2.4.x. We need to install cni first. 

but in ncp 2.5.x
there is no cni file and I guess we don't need to install it.
Am I correct??

If it is not, where is cni file in ncp 2.5.x folder??

**Comment by dumlutimuralp** [comment]
It is built into the bootstrap process, as part of NCP Bootstrap Pod. 

Mentioned here in the article = > https://github.com/dumlutimuralp/k8s-with-nsx-t-2.5.x/tree/master/Part%202#NSX-Components-in-K8S-Integration

All you need is the NCP image file. (tar file)

**Comment by joungwoongpark** [comment]
I got it. Thanks so much
